#!/bin/sh
set -e

[ -z ${@+x} ] && exit 1

dockerd > /var/log/dockerd.log 2>&1 &
sleep 2

IMAGES=${@}
for IMAGE in $IMAGES; do
    docker pull $IMAGE;
done

kill $(cat /var/run/docker.pid)
kill $(cat /run/docker/containerd/containerd.pid)
rm -f /var/run/docker.pid
rm -f /run/docker/containerd/containerd.pid
