services:

  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    working_dir: /app
    entrypoint: docker build -t hello-plankton .

  deploy:
    depends_on: build
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: docker run -d hello-plankton
