services:

  test:
    image: alpine
    command: echo Testing...

  build:
    image: alpine
    command: echo Building...
    depends_on:
      - test

  deploy:
    image: alpine
    command: echo Deploying...
    depends_on:
      - build
