#!/bin/bash
set -e

buildJar () {
    docker run -it --rm \
        -u $(id -u $USER):$(id -g $USER) \
        -v /etc/passwd:/etc/passwd:ro \
        -v $HOME/.m2/repository:$HOME/.m2/repository \
        -v $PWD:/workspace \
        -w /workspace \
        --entrypoint "" \
        maven:3.6-jdk-11 \
        mvn install
}

buildImage () {
    docker build -t adarlan/plankton .
}

buildSandbox () {
    docker build -t adarlan/plankton:sandbox -f sandbox/Dockerfile sandbox
}

# buildSandboxStuffed () {
    # TODO /etc/docker/daemon.json ADD -> "default-runtime": "sysbox-runc"
    # docker build -t adarlan/plankton:sandbox-stuffed \
    #     --build-arg "BUILT_IN_IMAGES=alpine docker" \
    #     -f sandbox/Dockerfile sandbox
    # TODO /etc/docker/daemon.json REMOVE -> "default-runtime"
# }

pushImages () {
    docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
    docker push adarlan/plankton
    docker push adarlan/plankton:sandbox
    # TODO docker push adarlan/plankton:sandbox-stuffed
}

if [ "$1" = "" ]; then
    set -exu
    buildJar && echo
    buildImage && echo
    buildSandbox && echo
    # buildSandboxStuffed

elif [ "$1" = "runner" ]; then
    set -exu
    buildJar && echo
    buildImage

elif [ "$1" = "sandbox" ]; then
    set -exu
    buildSandbox && echo
    # buildSandboxStuffed

elif [ "$1" = "--push" ]; then
    set -exu
    buildJar && echo
    buildImage && echo
    buildSandbox && echo
    # buildSandboxStuffed && echo
    pushImages
fi
