version: "3.7"

services:

  dockerflow:
    image: runner:dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERFLOW_WORKSPACE}:/workspace
    ports:
      - 1329:1329
    command: -Dspring-boot.run.arguments="--dockerflow.name=${DOCKERFLOW_NAME} --dockerflow.workspace=/workspace --dockerflow.environment=${DOCKERFLOW_ENVIRONMENT} --dockerflow.file=${DOCKERFLOW_FILE} --dockerflow.metadata=${DOCKERFLOW_METADATA}"

  mysql:
    image: foo-service
    #command: --port 80

  adminer:
    image: foo-service
    #command: --port 80
    labels:
      dockerflow.require.mysql.port: 80

  download:
    image: foo-task
    command: --time 60 --file /flags/downloaded
    volumes:
      - ./flags:/flags

  save-the-whales:
    image: ubuntu
    labels:
      dockerflow.target: true
      dockerflow.timeout: 3s
    entrypoint:
      - /bin/bash
      - -c
      - |
        echo hello
        echo goodbye

  import:
    image: foo-task
    command: --time 45
    volumes:
      - ./flags:/flags
    labels:
      dockerflow.timeout: 1h
      dockerflow.enable.if: '[ 0 = 1 ] && [ $$GIT_BRANCH = master ] || [ ! $${BAR:0:4} = bar- ]'
      dockerflow.wait.download.status: finished
      dockerflow.wait.mysql.port: 80
      dockerflow.wait.file: flags/downloaded

  docker-ls:
    image: docker
    command: sh -c 'docker ps'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
