services:
  # =====
  # BUILD
  # =====

  .build:

  build_plankton_jar:
    extends: .build
    image: maven:3.6-jdk-11
    entrypoint:
      - mvn package -DskipTests
    working_dir: /workspace
    volumes:
      - ./src:/workspace/src:ro
      - ./pom.xml:/workspace/pom.xml:ro
      - ./target:/workspace/target
      - .m2/repository:/root/.m2/repository

  build_plankton_image:
    extends: .build
    depends_on: build_plankton_jar
    image: docker:20.10
    entrypoint:
      - docker build -t adarlan/plankton .
    working_dir: /workspace
    volumes:
      - ./Dockerfile:/workspace/Dockerfile
      - ./target:/workspace/target
      - /var/run/docker.sock:/var/run/docker.sock

  build_plankton_sandbox_image:
    extends: .build
    image: docker:20.10
    entrypoint:
      - docker build -t adarlan/plankton:sandbox sandbox
    working_dir: /workspace
    volumes:
      - ./sandbox:/workspace/sandbox
      - /var/run/docker.sock:/var/run/docker.sock

  # ====
  # TEST
  # ====

  .test:
    image: adarlan/plankton
    command:
      - --spring.main.web-application-type=none
    working_dir: /workspace
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - .build

  .test_group_1:
    extends: .test

  .test_group_2:
    extends: .test
    depends_on:
      - .test_group_1

  .test_group_3:
    extends: .test
    depends_on:
      - .test_group_2

  test_binding-volumes:
    extends: .test_group_1
    volumes:
      - ./examples/binding-volumes:/workspace

  test_building-docker-image:
    extends: .test_group_1
    volumes:
      - ./examples/building-docker-image:/workspace

  # test_failing-on-blocked-job:
  #   extends: .test
  #   volumes:
  #     - ./examples/failing-on-blocked-job:/workspace

  # test_failing-on-dependency-loop:
  #   extends: .test
  #   volumes:
  #     - ./examples/failing-on-dependency-loop:/workspace

  test_running-parallel-jobs:
    extends: .test_group_2
    volumes:
      - ./examples/running-parallel-jobs:/workspace

  test_saying-hello-world:
    extends: .test_group_2
    volumes:
      - ./examples/saying-hello-world:/workspace

  test_scaling-jobs:
    extends: .test_group_3
    volumes:
      - ./examples/scaling-jobs:/workspace

  test_testing-web-application:
    extends: .test_group_3
    volumes:
      - ./examples/testing-web-application:/workspace

  # test_testing-web-application-with-database:
  #   extends: .test
  #   volumes:
  #     - ./examples/testing-web-application-with-database:/workspace

  # ===========
  # PUSH IMAGES
  # ===========

  .push_image:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - plankton.env
    entrypoint:
      - set -eu
      - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
      - docker push $IMAGE
    depends_on:
      - .test

  push_plankton_image:
    extends: .push_image
    environment:
      - IMAGE=adarlan/plankton

  push_plankton_sandbox_image:
    extends: .push_image
    environment:
      - IMAGE=adarlan/plankton:sandbox
