services:
  build_runner_jar:
    image: maven:3.6-jdk-11
    entrypoint: mvn package -DskipTests
    working_dir: /workspace
    user: 1001:1001
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ./:/workspace
      - /home/adarlan/.m2/repository:/home/adarlan/.m2/repository

  build_runner_image:
    depends_on: build_runner_jar
    build: .
    image: adarlan/plankton
    entrypoint: ""

  build_sandbox_image:
    build: sandbox
    image: adarlan/plankton:sandbox
    entrypoint: ""

  .test_runner:
    image: adarlan/plankton
    command: --plankton.project.path /workspace
    working_dir: /workspace
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  getting_started.test_runner:
    depends_on: build_runner_image
    volumes: ./examples/getting-started:/workspace

  demo_1.test_runner:
    depends_on: build_runner_image
    volumes: ./examples/demo-1:/workspace

  .push_image:
    image: docker
    volumes: /var/run/docker.sock:/var/run/docker.sock
    env_file: plankton.env
    entrypoint:
      - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
      - docker push $IMAGE

  runner.push_image:
    depends_on:
      - getting_started.test_runner
      - demo_1.test_runner
    environment: IMAGE=adarlan/plankton

  sandbox.push_image:
    depends_on: runner.push_image
    environment: IMAGE=adarlan/plankton:sandbox
