services:
  build_plankton_jar:
    image: maven:3.6-jdk-11
    entrypoint:
      - mvn package -DskipTests
    working_dir: /workspace
    volumes:
      - ./src:/workspace/src:ro
      - ./pom.xml:/workspace/pom.xml:ro
      - ./target:/workspace/target
      - .m2/repository:/root/.m2/repository

  build_plankton_image:
    depends_on: build_plankton_jar
    image: docker:20.10
    entrypoint:
      - docker build -t adarlan/plankton .
    working_dir: /workspace
    volumes:
      - ./Dockerfile:/workspace/Dockerfile
      - ./target:/workspace/target
      - /var/run/docker.sock:/var/run/docker.sock

  build_plankton_sandbox_image:
    image: docker:20.10
    entrypoint:
      - docker build -t adarlan/plankton:sandbox sandbox
    working_dir: /workspace
    volumes:
      - ./sandbox:/workspace/sandbox
      - /var/run/docker.sock:/var/run/docker.sock

  .test:
    image: adarlan/plankton
    command:
      - --spring.main.web-application-type=none
    working_dir: /workspace
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  test_building-docker-image:
    extends: .test
    depends_on: build_plankton_image
    volumes:
      - ./examples/building-docker-image:/workspace

  test_failing-on-blocked-job:
    extends: .test
    depends_on: test_building-docker-image
    volumes:
      - ./examples/failing-on-blocked-job:/workspace

  test_failing-on-dependency-loop:
    extends: .test
    depends_on: test_failing-on-blocked-job
    volumes:
      - ./examples/failing-on-dependency-loop:/workspace

  test_running-parallel-jobs:
    extends: .test
    depends_on: test_failing-on-dependency-loop
    volumes:
      - ./examples/running-parallel-jobs:/workspace

  test_saying-hello-world:
    extends: .test
    depends_on: test_running-parallel-jobs
    volumes:
      - ./examples/saying-hello-world:/workspace

  test_testing-web-application:
    extends: .test
    depends_on: test_saying-hello-world
    volumes:
      - ./examples/testing-web-application:/workspace

  # test_testing-web-application-with-database:
  #   extends: .test
  #   depends_on: test_testing-web-application
  #   volumes:
  #     - ./examples/testing-web-application-with-database:/workspace

  .push_image:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - plankton.env
    entrypoint:
      - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
      - docker push $IMAGE

  push_plankton_image:
    extends: .push_image
    environment:
      - IMAGE=adarlan/plankton
    depends_on:
      - test_building-docker-image
      - test_failing-on-dependency-loop
      - test_saying-hello-world
      - test_failing-on-blocked-job
      - test_running-parallel-jobs
      - test_testing-web-application
      # - test_testing-web-application-with-database

  push_plankton_sandbox_image:
    extends: .push_image
    environment:
      - IMAGE=adarlan/plankton:sandbox
    depends_on:
      - test_building-docker-image
      - test_failing-on-dependency-loop
      - test_saying-hello-world
      - test_failing-on-blocked-job
      - test_running-parallel-jobs
      - test_testing-web-application
      # - test_testing-web-application-with-database
