jobs:
  # =====
  # BUILD
  # =====

  .build:

  build_runner_jar:
    extends: .build
    image: maven:3.6-jdk-11
    entrypoint:
      - mvn package -DskipTests
    working_dir: /workspace
    volumes:
      - ./src:/workspace/src:ro
      - ./pom.xml:/workspace/pom.xml:ro
      - ./target:/workspace/target
      - .m2/repository:/root/.m2/repository

  build_runner_image:
    extends: .build
    depends_on: build_runner_jar
    image: docker:20.10
    entrypoint:
      - docker build -t adarlan/plankton .
    working_dir: /workspace
    volumes:
      - ./Dockerfile:/workspace/Dockerfile
      - ./target:/workspace/target
      - /var/run/docker.sock:/var/run/docker.sock

  build_sandbox_image:
    extends: .build
    image: docker:20.10
    entrypoint:
      - docker build -t adarlan/plankton:sandbox sandbox
    working_dir: /workspace
    volumes:
      - ./sandbox:/workspace/sandbox
      - /var/run/docker.sock:/var/run/docker.sock

  # ====
  # TEST
  # ====

  .test:
    image: adarlan/plankton
    command:
      - --spring.main.web-application-type=none
    working_dir: /workspace
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - .build

  test_binding-mounts:
    extends: .test
    volumes:
      - ./examples/binding-mounts:/workspace

  test_building-docker-image:
    extends: .test
    volumes:
      - ./examples/building-docker-image:/workspace

  test_running-parallel-jobs:
    extends: .test
    volumes:
      - ./examples/running-parallel-jobs:/workspace

  test_saying-hello-world:
    extends: .test
    volumes:
      - ./examples/saying-hello-world:/workspace

  test_scaling-job:
    extends: .test
    volumes:
      - ./examples/scaling-job:/workspace

  test_testing-failure:
    extends: .test
    volumes:
      - ./examples/testing-failure:/workspace

  test_writing-and-reading-file:
    extends: .test
    volumes:
      - ./examples/writing-and-reading-file:/workspace

  # ====
  # PUSH
  # ====

  .push_image:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - plankton.env
    entrypoint:
      - set -eu
      - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
      - docker push $IMAGE
    depends_on:
      - .test

  deploy_runner:
    extends: .push_image
    environment:
      - IMAGE=adarlan/plankton

  deploy_sandbox:
    extends: .push_image
    environment:
      - IMAGE=adarlan/plankton:sandbox
