#!/bin/bash
set -ex

cd $1
PROJECT_PATH=$PWD
COMPOSE_FILE=$PWD/plankton.compose.yaml
cd -

mvn spring-boot:run -Dspring-boot.run.arguments="--plankton.compose.file=$COMPOSE_FILE --plankton.project.directory=$PROJECT_PATH"
