#!/bin/bash
set -ex

NAME=$1
WORKSPACE=$PWD/examples/$NAME
COMPOSE_FILE=${WORKSPACE}/plankton.compose.yaml
METADATA=${WORKSPACE}/.plankton

cd local-runner

mvn spring-boot:run -Dspring-boot.run.arguments="--plankton.compose.file=$COMPOSE_FILE --plankton.workspace=$WORKSPACE --plankton.metadata=$METADATA"
