#!/bin/bash
set -ex

cd $1
WORKSPACE=$PWD
COMPOSE_FILE=$PWD/plankton.compose.yaml
cd -

mvn spring-boot:run -Dspring-boot.run.arguments="--plankton.compose.file=$COMPOSE_FILE --plankton.workspace=$WORKSPACE"
