#!/bin/bash
set -ex

./run-with-$1 examples/build-job-image
./run-with-$1 examples/demo-1
./run-with-$1 examples/demo-2
./run-with-$1 examples/getting-started
./run-with-$1 examples/pull-job-image
./run-with-$1 examples/wait-ports
