#!/bin/bash
set -ex

./run-with-mvn examples/build-job-image
./run-with-mvn examples/demo-1
./run-with-mvn examples/demo-2
./run-with-mvn examples/getting-started
./run-with-mvn examples/pull-job-image
./run-with-mvn examples/wait-ports
