#!/bin/bash
set -ex

TEST_APPLICATION="demo-1"

# run the local-runner container
[ $RUNNER = "local" ] && docker run -it --rm \
  -v $PWD/plankton-tests/$TEST_APPLICATION:/workspace \
  -w /workspace \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --network host \
  plankton:local-runner \
  --plankton.name=$TEST_APPLICATION \
  --plankton.file=plankton.compose.yml

# run the remote-runner container
[ $RUNNER = "remote" ] && docker run -it --rm \
  -v $PWD/plankton-tests/$TEST_APPLICATION:/workspace \
  -w /workspace \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --network host \
  plankton:remote-runner

if [ $RUNNER = "remote" ]; then
  docker stack rm plankton-runner || true
  sleep 5
  docker stop $(docker ps -a -q) || true
  sleep 5
  mkdir -p ~/.plankton/runner-1
  docker stack deploy --compose-file on-server/runners.docker-compose.yml plankton
  docker service logs --follow plankton_runner-1
fi
