services:
  terraform_plan:
    profiles:
      - create
    image: hashicorp/terraform
    volumes: ./:/working_dir
    working_dir: /working_dir
    entrypoint:
      - rm -rf tfplan
      - terraform init
      - terraform plan -out tfplan

  terraform_apply:
    profiles:
      - create
    depends_on: terraform_plan
    image: hashicorp/terraform
    volumes: ./:/working_dir
    working_dir: /working_dir
    entrypoint:
      - terraform init
      - terraform apply tfplan

  terraform_plan_destroy:
    profiles:
      - destroy
    image: hashicorp/terraform
    volumes: ./:/working_dir
    working_dir: /working_dir
    entrypoint:
      - rm -rf tfplan_destroy
      - terraform init
      - terraform plan -destroy -out tfplan_destroy

  terraform_apply_destroy:
    profiles:
      - destroy
    depends_on: terraform_plan_destroy
    image: hashicorp/terraform
    volumes: ./:/working_dir
    working_dir: /working_dir
    entrypoint:
      - terraform init
      - terraform apply tfplan_destroy
