version: "3.7"

services:

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    ports:
      - 3306:3306
  
  nginx:
    image: nginx
    ports:
      - 80:80

  check-port-3306:
    image: alpine
    command: echo Hello
    labels:
      plankton.wait.ports: 3306

  check-port-80:
    image: alpine
    command: echo Hello
    labels:
      plankton.wait.ports: 80
