#!/bin/bash
set -eu

sleepTime=${2}

echo "$(date '+%Y-%m-%d %H:%M:%S') hello"
sleep 1

msg=0
for (( i=1; i<$sleepTime; i++ ))
do
    if [ "${msg}" = "0" ]; then
        echo "$(date '+%Y-%m-%d %H:%M:%S') beep"
        msg=1
    else
        echo "$(date '+%Y-%m-%d %H:%M:%S') boop"
        msg=0
    fi
    sleep 1
done

if [ ! -z ${3+x} ]; then
    touch ${4}
fi

echo "$(date '+%Y-%m-%d %H:%M:%S') bye"
