version: "3.7"

services:

  alphabet:
    image: alpine
    command: ash -c 'for x in $$FOO; do echo $$x; sleep 1; done'
    environment:
      FOO: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"

  numbers:
    image: alpine
    command: ash -c 'for x in $$BAR; do echo $$x; sleep 1; done'
    environment:
      BAR: "0 1 2 3 4 5 6 7 8 9"
