jobs:
  build_app_image:
    image: docker
    working_dir: /app
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - docker build -t app .

  app:
    depends_on:
      build_app_image:
        condition: service_completed_successfully
    image: app

  test_app:
    depends_on:
      app:
        condition: service_started
    image: curlimages/curl
    environment:
      - URL=http://app
    entrypoint:
      - set -eu
      - HttpStatus=$(curl -sL -w "%{http_code}" -I $URL -o /dev/null)
      - test $HttpStatus = 200
