services:
  build_app_image:
    image: app
    build: .
    entrypoint: ""

  app:
    depends_on:
      build_app_image:
        condition: service_completed_successfully
    image: app

  test_app:
    depends_on:
      app:
        condition: service_started
    image: curlimages/curl
    entrypoint: curl http://app
