#!/bin/bash
set -ex

# docker stack rm plankton-runner || true
# sleep 5
# docker stop $(docker ps -a -q) || true
# sleep 5

mkdir -p ~/.plankton/runner-1
docker stack deploy --compose-file on-server/runners.docker-compose.yml plankton
docker service logs --follow plankton_runner-1
