jobs:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/app
    working_dir: /app
    entrypoint:
      - docker build -t hello-plankton .

  run:
    image: hello-plankton
    depends_on: build
