services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  app:
    image: nginx

  test_app:
    image: alpine
    command: echo foo
