jobs:
  foo:
    image: alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint:
      - cat foo.txt

  bar:
    image: alpine
    working_dir: /workspace
    volumes:
      - ./bar:/workspace
    entrypoint:
      - cat bar.txt
