jobs:
  foo:
    image: alpine
    environment:
      - FOO=A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
    entrypoint:
      - for x in $FOO; do echo $x; sleep 1; done

  bar:
    image: alpine
    environment:
      - BAR=0 1 2 3 4 5 6 7 8 9
    entrypoint:
      - for x in $BAR; do echo $x; sleep 1; done
